openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
  description: RESTful API for task management with user isolation

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /users/{user_id}/tasks:
    get:
      summary: List user tasks
      description: Retrieve all tasks for a specific user with pagination
      operationId: listUserTasks
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID (UUID format)
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Page number (1-based)
        - name: page_size
          in: query
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
          description: Items per page (max 100)
      responses:
        '200':
          description: List of tasks (may be empty)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: Create task
      description: Create a new task for a specific user
      operationId: createTask
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID (UUID format)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /users/{user_id}/tasks/{task_id}:
    get:
      summary: Get task by ID
      description: Retrieve a specific task by its ID for a user
      operationId: getTask
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID (UUID format)
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID (UUID format)
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Update task (full)
      description: Update all fields of an existing task
      operationId: updateTask
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID (UUID format)
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID (UUID format)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    patch:
      summary: Update task (partial)
      description: Update specific fields of an existing task
      operationId: partialUpdateTask
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID (UUID format)
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID (UUID format)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      summary: Delete task
      description: Delete a specific task
      operationId: deleteTask
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID (UUID format)
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID (UUID format)
      responses:
        '204':
          description: Task deleted successfully (no content)
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          example: "Buy groceries"
          description: Task title (required)
        description:
          type: string
          nullable: true
          example: "Milk, eggs, bread"
          description: Optional task description

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          example: "Buy groceries"
          description: Task title (optional for update)
        description:
          type: string
          nullable: true
          example: "Milk, eggs, bread"
          description: Optional task description
        is_completed:
          type: boolean
          example: true
          description: Completion status

    TaskResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
          description: Unique task identifier
        user_id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440001"
          description: Owning user identifier
        title:
          type: string
          example: "Buy groceries"
          description: Task title
        description:
          type: string
          nullable: true
          example: "Milk, eggs, bread"
          description: Optional task description
        is_completed:
          type: boolean
          example: false
          description: Completion status
        created_at:
          type: string
          format: date-time
          example: "2026-01-07T10:30:00Z"
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          example: "2026-01-07T10:30:00Z"
          description: Last update timestamp

    TaskListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponse'
        total:
          type: integer
          example: 42
          description: Total number of tasks
        page:
          type: integer
          example: 1
          description: Current page number
        page_size:
          type: integer
          example: 20
          description: Items per page
        total_pages:
          type: integer
          example: 3
          description: Total number of pages

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: "VALIDATION_ERROR"
              description: Error code
            message:
              type: string
              example: "Title is required"
              description: Human-readable error message
            details:
              type: object
              nullable: true
              description: Additional error details

  responses:
    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
